package com.kangdainfo.webapi.model.bo;
// Generated 2019/8/2 �U�� 06:32:34 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Exp0001Db generated by hbm2java
 */
@Entity
@Table(name = "EXP0001_DB", schema = "dbo", catalog = "IFI_DB")
public class Exp0001Db implements java.io.Serializable {

}
